version: "3.9"
services:
  redis:
    container_name: redis_ru102j
    image: "redislabs/redistimeseries"
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    entrypoint:
      redis-server
        --loadmodule /usr/lib/redis/modules/redistimeseries.so
        --appendonly yes
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
